<?php

return [

    "title" => env("SWAGGER_TITLE","Laravel Notebook API Documentation"),

    "description" => env("SWAGGER_DESCRIPTION", "Laravel autogenerated swagger"),

    "email" => env("SWAGGER_EMAIL","temp@mail.com"),

    "version" => env("SWAGGER_VERSION", "1.0.0"),

    "auth_middlewares" => [
        "auth",
        "auth:api"
    ],

    "url" => env("SWAGGER_URL", "swagger/documentation"),

    "enable" => env('SWAGGER_ENABLED', true),

    "show_prefix" => [],

    "servers" => [
        [
            "url" => env("APP_URL"),
            "description" => "localhost"
        ],
        [
            "url" => "http://localhost",
            "description" => "production"
        ],
    ],

    "security_schemes" => [
        "authorization" => [
            "type" => "apiKey",
            "name" => "authorization",
            "in" => "header"
        ],
    ]

];
